added truncate file option to context menu
LogExperts/LogExpert pull request #146
Opened 2019-12-03 21:11 UTC by jsuppe

I had found myself deleting the log file(s) repeatedly to get clean view for certain log files, especially when filters would be capturing too much. This option to truncate that log file improved my workflow.

2020-01-20 13:07 UTC, Hirogen commented on src/LogExpert/Controls/LogTabWindow/LogTabWindowEventHandlers.cs
> +
Does this take into account, if the file is not write able by another process?
This is not a safe way to create a new file => Exceptions are not taken into account!

2020-01-31 23:23 UTC, zarunbal commented
The easier way would be in my opinion to use the "external tools" feature. There you can launch any executable or e.g. cmd.exe with some commands.

2021-02-11 17:08 UTC, den-rain commented
I can vote for the feature to truncate a log file! It will be very helpful.

2022-07-24 14:49 UTC, jsuppe commented
New update to this branch checks for the file lock and writes to status what the process holding the lock is named. Also, this is now described as "try to" truncate, because it is not guaranteed. This change only aims to address when exception may be thrown due to trying to exclusively obtain write lock on file that already has lock and would then cause an exception.

2022-07-24 15:29 UTC, Hirogen commented
please merge the latest changes from the development branch, you got over 200 files, that would change back to an older version if I accepted that MR

2023-03-20 13:53 UTC, Hirogen requested changes
sorry for the late answer, could you please add unit testcases, otherwise it looks ok

2025-02-21 20:57 UTC, Neustradamus commented
@jsuppe: Can you update your draft PR?

2025-03-08 12:35 UTC, closed without merging